{
 "title": "Dashboard Express JS (Transaction Bancaire)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Métriques de l'application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nombre Total De Requêtes HTTP",
   "type": "stat",
   "description": "Nombre Total De Requêtes HTTP",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nodejs_http_total_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de requêtes HTTP par méthode (GET, POST, PUT, PATCH, DELETE)",
   "type": "stat",
   "description": "Nombre de requêtes HTTP par méthode (GET, POST, PUT, PATCH, DELETE)",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (nodejs_http_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "État des ressources du serveur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": " État des ressources du serveur (CPU, RAM, etc.)",
   "type": "barchart",
   "description": "Vérifier l'utilisation du CPU par l'application",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation de la mémoire ",
   "type": "histogram",
   "description": "Surveiller la mémoire libre",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": " node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}